services:
  # Servicio de la API Web (Flask)
  web:
    build: ./web
    container_name: task-manager-web
    ports:
      - "5001:5000"
    volumes:
      - ./web:/app  # Montaje para desarrollo en vivo
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/taskdb
      - RABBITMQ_URL=amqp://guest:guest@mq:5672/%2F
    depends_on:
      - db
      - mq

  # Servicio del Trabajador Asíncrono (Consumer)
  worker:
    build: ./worker
    container_name: task-manager-worker
    volumes:
      - ./worker:/app # Montaje para desarrollo en vivo
    environment:
      - RABBITMQ_URL=amqp://guest:guest@mq:5672/%2F
    depends_on:
      - mq

  # Servicio de la Base de Datos
  db:
    image: postgres:14-alpine
    container_name: task-manager-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskdb
    ports:
      - "5433:5432" # Exponer para depuración externa

  # Servicio del Bróker de Mensajes
  mq:
    image: rabbitmq:3-management-alpine
    container_name: task-manager-mq
    ports:
      - "5672:5672"   # Puerto para la comunicación AMQP
      - "8081:15672" # Puerto para la interfaz de gestión web
    
  # Servicio del Notificador
  notifier:
    build: ./notifier
    container_name: task-manager-notifier
    volumes:
      - ./notifier:/app # Montaje para desarrollo en vivo
    environment:
      - RABBITMQ_URL=amqp://guest:guest@mq:5672/%2F
      - WEBHOOK_URL=https://webhook.site/2e143480-debc-4ef8-9f88-5098af655480
    depends_on:
      - mq
      - web
      - worker
    
  # Servicio del Manejador de Errores
  error_handler:
    build: ./error_handler
    container_name: task-manager-error-handler
    volumes:
      - ./error_handler:/app # Montaje para desarrollo en vivo
    environment:
      - RABBITMQ_URL=amqp://guest:guest@mq:5672/%2F
    depends_on:
      - mq

volumes:
  postgres_data: